name: training
channels:
  - conda-forge
dependencies:
  - eccodes
  - cfgrib
  - xarray
  - pip
  - pip:
    - ecmwf-api-client==1.6.3
    - jupyter_contrib_nbextensions
    - jupyterlab
    - netcdf4
    - ipykernel
    - kaleido
    - covjsonkit
    - lxml
    - nbformat
    - earthkit-regrid
    - earthkit-data
    - earthkit-geo
    - earthkit-utils
    - earthkit-plots==0.3.2
